lib/puppetserver/ca/cli.rb, lib/puppetserver/ca/import_action.rb, spec/puppetserver/ca/cli_spec.rb
This commit renames the `setup` subcommand to `import`, to better
differentiate it from `generate`, which also sets up a CA.
=> (SERVER-2261) Rename puppetserver-ca's `setup` command to `import`

Gemfile, lib/puppetserver/ca/config_utils.rb, lib/puppetserver/ca/puppet_config.rb, lib/puppetserver/ca/puppetserver_config.rb, spec/puppetserver/ca/puppetserver_config_spec.rb
This commit adds a PuppetserverConfig class responsible for parsing
CA-related settings out of Puppetserver's CA config file. This file is
written in HOCON, so this commit pulls in the ruby-hocon gem for parsing
the file.
=> (SERVER-2254) Allow the CLI to read from puppetserver's config

lib/puppetserver/ca/cli.rb, lib/puppetserver/ca/sign_action.rb, lib/puppetserver/utils/file_utilities.rb, lib/puppetserver/utils/http_utilities.rb, spec/puppetserver/ca/cli_spec.rb, spec/puppetserver/ca/sign_action_spec.rb
This is still a work in progress, but I thought it might be nice to get some feedback. The main chunk of work is the logic in ``puppetserver/ca/sign_action.rb`` differentiating between use with and without the ``--all`` flag. I'm not sure all of the parsing logic stands, but I've tested it manually in the irb and I can confirm that it's signing certs. The rest is just getting it pretty/efficient, and I'm starting to write the spec.
=> (SERVER-1714) Add sign action

lib/puppetserver/ca/clean_action.rb, lib/puppetserver/ca/cli.rb, lib/puppetserver/utils/http_utilities.rb, spec/puppetserver/ca/clean_action_spec.rb
This provides a clean action. The inputs (and their validation) is the same as the `revoke` action. The actual action is a superset of revocation (send a PUT to revoke and then a DELETE to clean up after ourselves). Consequently a lot of this is directly boilerplate from revoke.
I assume we might want to create a CA object that we can delegate the shared behaviors and validation to? Thought I'd run doing that by folks (in this or another PR).
At a minimum this needs a rebase, but I'ld love to get folks feedback on the approach/see if I'm missing anything.
=> (SERVER-2259) Add clean action

lib/puppetserver/ca/clean_action.rb, lib/puppetserver/ca/revoke_action.rb, lib/puppetserver/ca/sign_action.rb, lib/puppetserver/utils/http_client.rb, spec/puppetserver/ca/clean_action_spec.rb, spec/puppetserver/ca/revoke_action_spec.rb, spec/puppetserver/utils/http_client_spec.rb
Refactor to create an actual HTTP client object that
initializes SSL state once and stores it, allowing
multiple connections to be made from it.
=> (SERVER-2275) Refactor code to make an HTTP client

lib/puppetserver/ca/sign_action.rb, spec/puppetserver/ca/sign_action_spec.rb
When --all flag is included we ask for all csrs from
the CA.  Code is returned in string format so we must
read it as such.
=> (maint) Allow 200 response to process correctly

lib/puppetserver/ca/action/generate.rb, lib/puppetserver/ca/action/sign.rb, lib/puppetserver/ca/config/puppet.rb, spec/puppetserver/ca/action/generate_spec.rb, spec/puppetserver/ca/utils/http_client_spec.rb
This commit updates the `generate` action to also create a master
certificate signed by the intermediate CA. This cert support subect
alternative names that can be customized via Puppet's dns_alt_names
setting or the `--subject-alt-names` flag.
=> (SERVER-2286) Create a master cert as part of `generate` action

lib/puppetserver/ca/action/generate.rb, lib/puppetserver/ca/action/import.rb, lib/puppetserver/ca/utils/file_system.rb, spec/puppetserver/ca/action/generate_spec.rb, spec/puppetserver/ca/action/import_spec.rb, spec/puppetserver/ca/utils/http_client_spec.rb
Supersedes https://github.com/puppetlabs/puppetserver-ca-cli/pull/18
=> (maint) Prevent `generate` and `import` from overwriting existing CA files

lib/puppetserver/ca/action/list.rb, lib/puppetserver/ca/local_certificate_authority.rb, spec/puppetserver/ca/action/generate_spec.rb, spec/puppetserver/ca/action/import_spec.rb, spec/puppetserver/ca/local_certificate_authority_spec.rb
This commit adds a new custom extension to the master cert when
generating it. This extension is checked by tk-auth when allowing access
to the certificate_status and certificate_statuses endpoints. This is to
help ensure that only requests from the puppet master's cert can access
those endpoints.
=> (SERVER-2287) Add custom auth extension to master cert

lib/puppetserver/ca/action/create.rb, spec/puppetserver/ca/action/create_spec.rb
Previously we passed a bare string into Extension.new, which would not
do the special pre-processing that an ExtensionFactory will do for us to
ensure that subjectAltNames were properly encoded. Because what was
encoded was a string, the printing and manual inspection lead us to
believe that everything was encoded properly, however the
ExtensionFactory will create a sequence with elements typed by their
kind of name (eg DNS or IP). More rigorous CA code was not allowing the
encoded string in the place of what should have been an encoded
sequence.
This moves us to use the ExtensionFactory so we do not need to care
about the convoluted nature of CSR encoding. It also adds a test to
prove that what is encoded in our CSRs are sequences that can be decoded
into their correct individual …
=> (maint) Correctly encode SAN extReqs in CSRs

lib/puppetserver/ca/action/clean.rb, lib/puppetserver/ca/action/revoke.rb, lib/puppetserver/ca/certificate_authority.rb, spec/puppetserver/ca/action/clean_spec.rb, spec/puppetserver/ca/action/revoke_spec.rb
I don't know, seems like a weird behavior to keep.
=> (maint) Return 24 when revoking or cleaning unsigned CSRs

lib/puppetserver/ca/action/generate.rb, lib/puppetserver/ca/config/puppet.rb, lib/puppetserver/ca/config/puppetserver.rb, lib/puppetserver/ca/local_certificate_authority.rb, lib/puppetserver/ca/utils/config.rb, spec/puppetserver/ca/action/generate_spec.rb, spec/puppetserver/ca/action/setup_spec.rb, spec/puppetserver/ca/local_certificate_authority_spec.rb, spec/utils/ssl.rb
The cert used by the CA CLI needs to have a special auth extension that
is disallowed by the Puppet Server CA, to prevent any node from
requesting a cert with the special permissions. Previously, this cert
was always created along with the rest of the CA files.
This commit adds a way to generate an authorized cert with the special
extension, from an existing CA. The special cert is signed offline, not
through the main Puppet CA. It can be generated with values for the
master, or with values for other nodes. In the latter case the cert and
keys will need to be distributed manually.
This also updates `generate` to not use the `subject_alt_names`
setting. This setting is supposed to be specific to the master node, but
`generate` can be used to create certs for any node, and those shouldn't …
=> (SERVER-2320) Allow generation of an authorized cert offline

lib/puppetserver/ca/action/import.rb, spec/shared_examples/setup.rb
Previously we were not extracting the CA's public key into a publicly
visible file when using the import command. This commit remedies that
and adds a test for it.
=> (maint) Create ca_pub file when importing a CA

lib/puppetserver/ca/action/generate.rb, spec/puppetserver/ca/action/generate_spec.rb
Previously if the user tried to generate a cert that was autosigned by
the CA, the command would error, because it would request that the cert
be signed after it was already signed by autosign. This commit updates
the generate logic to take into account autosigning.
=> (SERVER-2345) Support autosigning when generating certs

lib/puppetserver/ca/action/generate.rb, lib/puppetserver/ca/certificate_authority.rb, lib/puppetserver/ca/utils/http_client.rb, spec/puppetserver/ca/action/generate_spec.rb
In order to avoid race conditions with serial numbers, we want to
avoid allowing multiple processes to issue certificates at the same
time. This commit adds a check to make sure that Puppet Server's CA
service is offline before issuing certs out-of-band using Ruby code,
when using `generate --ca-client`. It queries the simple status endpoint
and errors if it receives a "running" response from the server.
=> (SERVER-2351) Check CA service before generating certs offline

lib/puppetserver/ca/action/generate.rb, lib/puppetserver/ca/action/import.rb, lib/puppetserver/ca/action/setup.rb, lib/puppetserver/ca/local_certificate_authority.rb, spec/puppetserver/ca/local_certificate_authority_spec.rb, spec/puppetserver/ca/utils/http_client_spec.rb
Before this change, no state about the local CA was kept in memory; this
change introduces instance variables for cert, key, and crl to the class
and allows for them to be read from an object if the necessary files
existed.
=> (SERVER-2335) Refactor LocalCertificateAuthority

lib/puppetserver/ca/action/generate.rb, lib/puppetserver/ca/errors.rb, lib/puppetserver/ca/utils/http_client.rb, spec/puppetserver/ca/action/generate_spec.rb, spec/puppetserver/ca/errors_spec.rb
From 03da206 which implements most of this functionality:
```
Previously, we were catching ECONNREFUSED to determine if the server was
up. When we moved to custom error classes we no longer raise an
ECONNREFUSED, instead raising ConnectionFailed in it (and many other
potential exceptions) place.
So we should now be rescuing ConnectionFailed, but we only want to
swallow exceptions that originated from ECONNREFUSED, re-raising
ConnectionFaileds that originate from other exceptions.
To do so we add the ability to wrap an exception in our custom Error
class and update appropriate places where we were raising.
```
=> (SERVER-2401) Handle new exceptions when checking CA status

lib/puppetserver/ca/action/enable.rb, spec/puppetserver/ca/action/enable_spec.rb
Puppet Server will always generate an `infra_serials` file based on the
contents of `infra_inventory` on startup when the Infra CRL is enabled.
Therefore, the gem doesn't need to try to create it and doesn't need to
block if it is already present. This will help with some weird upgrade
scenarios where an inventory and infra_serials file are present, but the
CRL itself is not.
=> (SERVER-2478) Do not create an `infra_serials` file

lib/puppetserver/ca/action/enable.rb
This commit updates `puppetserver ca enable --infracrl` to check the CA
state for errors before attempting to generate the infrastructure CRL.
Prior to this commit, errors encountered when loading the CA state would
cause instance variables such as the certificate and private key to be
unset. This would result in CRL creation failing due to unexpected `nil`
values without providing clear messaging as to the root cause of the
problem.
=> (SERVER-2559) Check CA for errors before enabling infra crl

lib/puppetserver/ca/local_certificate_authority.rb, lib/puppetserver/ca/x509_loader.rb, spec/puppetserver/ca/action/import_spec.rb, spec/puppetserver/ca/utils/http_client_spec.rb, spec/utils/ssl.rb
Instead of requiring the signing certificate to be first in the certificate
bundle, find the certificate that matches the private key for the CA, and find
the CRL that is issued by that certificate.
=> (SERVER-2465) Find signing cert and crl based on private key

lib/puppetserver/ca/action/list.rb, spec/puppetserver/ca/action/list_spec.rb
The new --certname option on the list action behaves similiarly to how
the option operates on other actions, in this case by limiting the
output to the certnames specified, and causing the command to return a
non-zero exit code in the event a certname specified is not able to be
listed (because it is not present).
This brings `puppetserver ca list` closer to parity with older commands
such as `puppet cert list`.
Initial implementation is not performance optimized. It doesn't look
like the certificate_statuses API actually supports returning a filtered
list, so this commit is forced to filter the results of requesting all
certificate statuses.
=> (SERVER-2589) Add a --certname option to `list` action

puppetserver-ca.gemspec
This makes it possible to run the executable with bundler from a git
checkout.
=> (maint) Add executable to gemspec

lib/puppetserver/ca/local_certificate_authority.rb, spec/puppetserver/ca/local_certificate_authority_spec.rb
Prior to this PR, the serial file was converted to an integer from a string which would incorrectly round alphabetic digits. This commit ensures that reading and writing the serial file in hex format.
=> (SERVER-2603) Read and write the serial file in hex

lib/puppetserver/ca/action/import.rb, lib/puppetserver/ca/local_certificate_authority.rb, lib/puppetserver/ca/x509_loader.rb, spec/puppetserver/ca/action/import_spec.rb
This commit updates the `puppetserver ca import` command to initialize
a CRL for the intermediate CA if the loader does not find one in the
`crl-chain` file. Not having a pre-generated CRL is the typical case as
creating a CRL requires access to the private key of the intermediate
CA. An external CA generally should not have access to this key and is
therefore not able to provide a pre-generated CRL along with the
intermediate CA cert.
=> (SERVER-2552) Initialize leaf CRL during import

lib/puppetserver/ca/action/generate.rb, lib/puppetserver/ca/action/sign.rb, lib/puppetserver/ca/certificate_authority.rb, spec/puppetserver/ca/action/generate_spec.rb, spec/puppetserver/ca/action/sign_spec.rb
This change adds in the ability to specify a ttl for the generate and
sign actions.
=> (PE-27489) Add ability to specify ttl

puppetserver-ca.gemspec
This commit loosens the version restriction for Facter to allow Facter
4, the new Ruby re-write.
=> (SERVER-2727) Allow using Facter 4

puppetserver-ca.gemspec
This commit bumps the rake dependency in order to address CVE-2020-8130.
=> (maint) Bump rake dependency to >= 12.3.3

lib/puppetserver/ca/action/clean.rb, lib/puppetserver/ca/action/enable.rb, lib/puppetserver/ca/action/generate.rb, lib/puppetserver/ca/action/import.rb, lib/puppetserver/ca/action/list.rb, lib/puppetserver/ca/action/migrate.rb, lib/puppetserver/ca/action/revoke.rb, lib/puppetserver/ca/action/setup.rb, lib/puppetserver/ca/action/sign.rb, lib/puppetserver/ca/config/puppet.rb, spec/puppetserver/ca/action/clean_spec.rb, spec/puppetserver/ca/action/migrate_spec.rb, spec/puppetserver/ca/action/revoke_spec.rb, spec/puppetserver/ca/config/puppet_spec.rb, spec/puppetserver/ca/local_certificate_authority_spec.rb, spec/puppetserver/ca/utils/http_client_spec.rb, spec/spec_helper.rb, spec/utils/helpers.rb
With Puppet 7 the cadir location will move by default from `$ssldir` to
Puppet Server's confdir. However we want to respect any users that have
already created their cadir in either the old default location or a new
location. We also want to warn if they have it in the old location that
they should migrate the cadir. If users have a custom cadir but it
resides in the ssldir we also want to warn, a cadir within the ssldir
may cause accidental deletion of the cadir.
=> (SERVER-2896) Update defaults for new cadir

README.md, lib/puppetserver/ca/action/import.rb, lib/puppetserver/ca/action/setup.rb, lib/puppetserver/ca/config/puppet.rb, lib/puppetserver/ca/utils/config.rb, lib/puppetserver/ca/utils/file_system.rb, puppetserver-ca.gemspec, spec/puppetserver/ca/config/puppet_spec.rb, spec/shared_examples/setup.rb, spec/utils/ssl.rb
This commit adds a method to symlink the new default cadir to the old default
cadir location when running the `setup` and `import` commands. This ensures
that, even on new installs, we can access the cadir from the old location
because there are still tools in the ecosystem that expect the old location.
=> (SERVER-2895) Symlink to old cadir when setting up with the new default

lib/puppetserver/ca/action/enable.rb, lib/puppetserver/ca/action/generate.rb, lib/puppetserver/ca/action/import.rb, lib/puppetserver/ca/action/migrate.rb, lib/puppetserver/ca/action/setup.rb, lib/puppetserver/ca/config/puppet.rb, spec/puppetserver/ca/action/migrate_spec.rb, spec/puppetserver/ca/config/puppet_spec.rb, spec/puppetserver/ca/local_certificate_authority_spec.rb, spec/puppetserver/ca/utils/http_client_spec.rb
This commit adds an internal flag to disable the warning about using the
old CA dir location, so that it can be disabled when running the
`migrate` command.
=> (SERVER-2931) Do not warn about old CA dir location when migrating

lib/puppetserver/ca/action/generate.rb, spec/puppetserver/ca/action/generate_spec.rb
We previously updated the certificate signing code in puppetserver
proper to always add the certname as a subject alt name when signing a
certificate. This commit updates the `generate` action of the CLI gem to
also ensure that the certname of the host the cert is being generated
for is added as an alt name. Because `generate` is used to create certs
for other hosts, we can't use the value of `certname` from settings in
the CA code itself, but rather need to use the value of `certname` that
is passed into the command.
=> (SERVER-2338) Ensure `ca-client` cert has certname as altname

lib/puppetserver/ca/config/puppet.rb, spec/puppetserver/ca/config/puppet_spec.rb
The `default_certname` method would do the right thing the first time it
was called, and then afterwards fail to get the hostname. This commit
fixes the bad short circuiting logic.
=> (maint) Fix bad memoization in default certname

lib/puppetserver/ca/config/puppet.rb, lib/puppetserver/ca/utils/config.rb, spec/puppetserver/ca/config/puppet_spec.rb
This commit updates the settings resolution logic to detect when the CA
dir has been migrated, to return the new location in that case. If the
new dir does not have CA content, the old location is returned
(including if no dir exists).
=> (SERVER-2993) Detect migrated CA dir when calcuating settings

README.md, lib/puppetserver/ca/action/clean.rb, lib/puppetserver/ca/action/generate.rb, lib/puppetserver/ca/action/import.rb, lib/puppetserver/ca/action/revoke.rb, lib/puppetserver/ca/action/setup.rb, lib/puppetserver/ca/config/puppet.rb, lib/puppetserver/ca/host.rb, lib/puppetserver/ca/local_certificate_authority.rb, lib/puppetserver/ca/utils/http_client.rb, spec/puppetserver/ca/config/puppet_spec.rb, spec/puppetserver/ca/local_certificate_authority_spec.rb, spec/shared_examples/setup.rb
Update internal terminology, replacing master with server and blacklist with
denylist. The only user facing change here is updating the cli to correctly
read `serverport` from `puppet.conf` as a newer name for `masterport`.
=> (SERVER-2932) Update terminology in ca cli

README.md, lib/puppetserver/ca/certificate_authority.rb, lib/puppetserver/ca/cli.rb, lib/puppetserver/ca/logger.rb, lib/puppetserver/ca/utils/http_client.rb, spec/puppetserver/ca/cli_spec.rb, spec/puppetserver/ca/utils/http_client_spec.rb, spec/shared_examples/cli_parsing.rb
There are more changes like adding the logger to certain methods in `http_client.rb` but I elected not to include that in this PR.
=> (SERVER-2251) Add '--verbose' flag to 'puppetserve ca' cli tool

lib/puppetserver/ca/utils/http_client.rb
Reformat the output of the URL for the logger in verbose mode.
=> (SERVER-2251) Add '--verbose' flag to 'puppetserver ca' cli tool

README.md
The old URLs have been removed.
=> (maint) Update links to Jenkins jobs

lib/puppetserver/ca/action/list.rb, spec/puppetserver/ca/action/list_spec.rb
Here's a sample output in JSON format execute by `list --certname tu --format json | python -m json.tool` (Piped through python for pretty print)
```
[
{
"authorization_extensions": {},
"dns_alt_names": [
"DNS:tu"
],
"fingerprint": "18:52:07:6E:6F:E0:42:40:20:75:B8:80:0F:5D:26:94:0A:22:DC:2A:DD:67:81:90:BA:B3:13:8D:AD:B3:B5:95",
"fingerprints": {
"SHA1": "74:6F:63:4B:94:0B:EE:EE:1F:D9:60:DD:36:9D:E8:76:6C:A0:38:F7",
"SHA256": "18:52:07:6E:6F:E0:42:40:20:75:B8:80:0F:5D:26:94:0A:22:DC:2A:DD:67:81:90:BA:B3:13:8D:AD:B3:B5:95",
"SHA512": "F7:0D:4E:C0:8C:A8:8A:8C:2B:5B:49:27:63:EB:39:C5:26:B7:DB:28:E8:7D:63:DD:E1:BF:E8:B6:06:A4:28:44:48:FD:81:89:EB:37:7E:54:12:9C:4D:1C:EC:63:63:A4:70:11:E8:08:F1:90:F5:B2:6C:99:CE:6A:03:C5:7A:4A",
"default": …
```
=> (SERVER-3006) Provide parsable (json) output for puppetserver ca commands

README.md, lib/puppetserver/ca/action/list.rb, lib/puppetserver/ca/certificate_authority.rb, lib/puppetserver/ca/cli.rb, lib/puppetserver/ca/logger.rb, lib/puppetserver/ca/utils/http_client.rb, spec/puppetserver/ca/action/list_spec.rb, spec/puppetserver/ca/cli_spec.rb, spec/puppetserver/ca/utils/http_client_spec.rb
Puppetserver-ca CLI now has a verbose option that can be trigger by using the '--verbose' flag.  It can also output certificate depends on the user's choice of format.  As of now, the supported format are: text (default) and JSON.
=> Merge 1.x to main

lib/puppetserver/ca/action/prune.rb, spec/puppetserver/ca/action/prune_spec.rb
This commit contains a fix to the prune action so that the CRL number is properly updated after pruning.  Before, the code would update the protocol version which is incorrect.
=> (SERVER-2740) Fix how CRL number is updated

lib/puppetserver/ca/certificate_authority.rb, spec/puppetserver/ca/action/clean_spec.rb, spec/puppetserver/ca/action/revoke_spec.rb
Update the output message upon revoking a certificate, whether that cert is signed or revoked, to convey a more reassuring tone that the action is successful.
=> (SERVER-2509) Update output message for revoke action

lib/puppetserver/ca/action/list.rb, lib/puppetserver/ca/certificate_authority.rb, lib/puppetserver/ca/utils/http_client.rb, spec/puppetserver/ca/action/list_spec.rb, spec/puppetserver/ca/utils/http_client_spec.rb
This commits modified the `puppetserver ca list` command to only walk the directory of certificate requests when the user
want to get certificate requests. This should improve the speed when running the command `puppetserver ca list` without any option flags.
=> (SERVER-3060) Improve speed when querying for CSR only

lib/puppetserver/ca/action/prune.rb, lib/puppetserver/ca/utils/http_client.rb, spec/puppetserver/ca/action/prune_spec.rb
This PR includes:
- Bug fixes related to the recently added functionality of accepting a query parameter when constructing URL.
- Update output information for `prune` command to include the number of certificates found in Puppet's CRL.
- Update `prune` command to only take Puppet's CA CRL, no longer taking a list.
=> (maint) Bug fixes and update for `prune` command

lib/puppetserver/ca/action/prune.rb, lib/puppetserver/ca/utils/http_client.rb, spec/puppetserver/ca/action/prune_spec.rb
This merge contains:
- Update to `prune` action to specifically prune only Puppet's CA CRL and output message of total certificates found before pruning.
- Fix a bug when not checking for `:query` params to be `nil` when creating a URL.
=> Merge 1.x branch

lib/puppetserver/ca/action/list.rb, spec/puppetserver/ca/action/list_spec.rb
(SERVER-2797) Add failure exit code when `puppetserver ca list` hits errors.
When running a `puppetserver ca` command on a non-CA server, the command exits with a 0 = ok, when the command has obviously failed.  The failure is easily detected by a human, but less so for a computer.
This seeks to distinguish "failed at looking up" from "found no certificates" and exit accordingly.
=> Add failure exit code to puppetserver ca list, SERVER-2797

lib/puppetserver/ca/action/list.rb, spec/puppetserver/ca/action/list_spec.rb
When running a puppetserver ca command on a non-CA server, the command exits with a 0 = ok, when the command has obviously failed. The failure is easily detected by a human, but less so for a computer.
This seeks to distinguish "failed at looking up" from "found no certificates" and exit accordingly.
=> (SERVER-2797) Add failure exit code when `puppetserver ca list` hits errors.

lib/puppetserver/ca/action/prune.rb, lib/puppetserver/ca/utils/inventory.rb, spec/puppetserver/ca/action/migrate_spec.rb, spec/puppetserver/ca/local_certificate_authority_spec.rb, spec/puppetserver/ca/utils/http_client_spec.rb, spec/puppetserver/ca/utils/inventory_spec.rb
This adds a module for parsing the inventory.txt file. This will handle any errors found in the file, and return a hash with certname as the key and the rest of the info has another hash.  Because the inventory will likely have old entries for a given certname, this records the serials for the old certnames, but the serial value will be the latest cert found.
Also fixes a couple issues found, mostly around spec files not getting cleaned up due to the way some of the tests were written.
=> (PE-34952) Add inventory library

lib/puppetserver/ca/action/prune.rb, spec/puppetserver/ca/action/prune_spec.rb
Update prune command to take serialnumber(s) or certname(s) and remove corresponding entries from CRL. When serial numbers are given, the CRL will be searched for matching entries and will be deleted. If certnames are given, inventory.txt file will be searched for a matching certname, if found the corresponding serial number will be read and deleted from CRL. If the certname is not in inventory.txt, CA dir will be searched for a matching certificate and correspoding serial number will be deleted from CRL.
=>  PE-35371 Update prune command

lib/puppetserver/ca/action/delete.rb, lib/puppetserver/ca/cli.rb, spec/puppetserver/ca/action/delete_spec.rb, spec/utils/ssl.rb
This adds the `puppetserver ca delete` action, which deletes signed certs on disk without revoking them. While all the flags are defined here, only --expired is implemented so far (maybe not ideal, but the others are coming soon). This searches the inventory file for any expired certs, deletes them, then finds any certs that are not in the inventory file, checks if they are expired, and deletes those.
=> (PE-34952) Add delete action with --expired flag

lib/puppetserver/ca/action/delete.rb, spec/puppetserver/ca/action/delete_spec.rb
This adds the action for the --certname flag. This can be used in conjunction with other flags to provide an extra certname to delete.
=> (PE-34952) Add --certname action and other cleanup

lib/puppetserver/ca/action/delete.rb, spec/puppetserver/ca/action/delete_spec.rb, spec/puppetserver/ca/local_certificate_authority_spec.rb, spec/utils/ssl.rb
This inspects the CRL for a list of revoked serials. It then searches inventory.txt for those serials. If the given serial is the latest one for the particular certname, it puts it on a list for deletion (although it may in fact already be deleted). If it's an old serial for a particular certname, it verifies the cert on disk is a later serial. If for some reason it isn't, it removes the cert on disk as it matches the serial in the CRL. If it isn't in inventory.txt at all, it searches all certs on disk for the given serial. If it's found, it adds that cert to the list for deletion. It then deletes all relevant certs that exist.
=> (PE-34952) Add --revoked action

lib/puppetserver/ca/action/delete.rb, lib/puppetserver/ca/cli.rb, spec/puppetserver/ca/action/delete_spec.rb
This deletes all certs in the signed directory, and must be used by itself.
Additionally, this tweaks the behavior of puppetserver ca delete --expired to not print an error when a cert listed in the inventory is not found on disk, since this will happen when you run the command multiple times and we don't really want people messing with inventory.txt manually to get rid of this error.
=> (PE-35382) Add --all action

lib/puppetserver/ca/utils/http_client.rb, spec/puppetserver/ca/action/generate_spec.rb, spec/puppetserver/ca/utils/http_client_spec.rb
Checking if token file exists, if it does it will read the contexts and add it as a header for put requests.
=> (PE-35330) Load users token if available and use with CA endpoint

spec/puppetserver/ca/action/generate_spec.rb
This fixes a test suite error when building with OpenSSL 3.1 or later:
```
1) Puppetserver::Ca::Action::Generate downloading with a csr_attributes file return nil for csr if attribute name provided is private
Failure/Error: _, csr = subject.generate_key_csr('foo', settings, OpenSSL::Digest::SHA256.new)
OpenSSL::X509::RequestError:
duplicate attribute
```
By using another private x509 attribute which is not already defined in the custom_attributes file, the test case passes.
=> Fix duplicate attribute error with OpenSSL 3.1+

README.md
This removes references to the now defunct tickets.puppetlabs.com and references to the release pipeline.
It adds mentions of github issues for tracking requests and bug reports.
=> (maint) update README

lib/puppetserver/ca/action/setup.rb, lib/puppetserver/ca/config/puppet.rb, spec/puppetserver/ca/action/setup_spec.rb, spec/puppetserver/ca/config/puppet_spec.rb, spec/shared_examples/setup.rb
Adds command line parameter for the root ca name, and supports spaces in the ca_name and root_ca_name values when parsed from the config file.
=> (SERVER-2691) configurable root ca name

lib/puppetserver/ca/action/sign.rb, lib/puppetserver/ca/certificate_authority.rb, lib/puppetserver/ca/utils/http_client.rb, spec/puppetserver/ca/action/sign_spec.rb
Now that we have the /sign and /sign/all endpoints, this modifies the code to use these endpoints when the server version is 8.4.0+ or newer with these endpoints. Because the endpoints don't support setting the TTL, this falls back to the /certificate_status endpoint if TTL is specified.
=> (PE-37501) Use bulk signing endpoints when possible
